compatibility_date = "2023-12-01" 
main = "src/index.js" # 这是你构建的 Worker 入口文件路径
name = "cloudflare-docker-proxy" 

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
CUSTOM_DOMAIN = "exmaple.com"
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  {pattern = "docker.shaw123t.top", custom_domain = true},
  {pattern = "quay.shaw123t.top", custom_domain = true},
  {pattern = "gcr.shaw123t.top", custom_domain = true},
  {pattern = "k8s-gcr.shaw123t.top", custom_domain = true},
  {pattern = "k8s.shaw123t.top", custom_domain = true},
  {pattern = "ghcr.shaw123t.top", custom_domain = true},
  {pattern = "cloudsmith.shaw123t.top", custom_domain = true},
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = {pattern = "docker-staging.shaw123t.top", custom_domain = true}

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
